/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmk.logistics;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class Tabs extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Tabs
     */
    public Tabs() {
        initComponents();
        //connect to DB
        con = DBconnect.connect();

    }

    private void btableload() {
        try {
            String nq = "SELECT * FROM branch ";
            pst = con.prepareStatement(nq);
            rs = pst.executeQuery(nq);
            tblBranch.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Oops! Something went wrong!\n" + e,
                    "Message",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void vtableload() {
        try {
            String nq_ = "SELECT * FROM vehicle ";
            pst = con.prepareStatement(nq_);
            rs = pst.executeQuery(nq_);
            tblVehicle.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Oops! Something went wrong!\n" + e,
                    "Message",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void ctableload() {
        try {
            String nnq = "SELECT * FROM customer ";
            pst = con.prepareStatement(nnq);
            rs = pst.executeQuery(nnq);
            tblCustomer.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Oops! Something went wrong!\n" + e,
                    "Message",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void etableload() {
        try {
            String nnq = "SELECT * FROM employee ";
            pst = con.prepareStatement(nnq);
            rs = pst.executeQuery(nnq);
            tblEmployee.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Oops! Something went wrong!\n" + e,
                    "Message",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnCView = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnCSearch = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnCAdd = new javax.swing.JButton();
        btnCUpdate = new javax.swing.JButton();
        btnCDelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        txtBrId = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnCalcSal = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnEView = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtEName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnESearch = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtEid = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtEContact = new javax.swing.JTextField();
        txtEBSal = new javax.swing.JTextField();
        btnEAdd = new javax.swing.JButton();
        btnEUpdt = new javax.swing.JButton();
        btnEDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnVUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtVIn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbVType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        type = new javax.swing.JRadioButton();
        insNo = new javax.swing.JRadioButton();
        txtVehicle = new javax.swing.JTextField();
        btnVSearch = new javax.swing.JButton();
        btnVAdd = new javax.swing.JButton();
        btnVDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();
        btnVView = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtVinExp = new javax.swing.JTextField();
        txtVid = new javax.swing.JTextField();
        txtBBrId = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranch = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBrName = new javax.swing.JTextField();
        btnBSearch = new javax.swing.JButton();
        btnBView = new javax.swing.JButton();
        bnamebox = new javax.swing.JLabel();
        baddressbox = new javax.swing.JLabel();
        bcontactbox = new javax.swing.JLabel();
        txtBBrName = new javax.swing.JTextField();
        txtBBrAddress = new javax.swing.JTextField();
        txtBBrContact = new javax.swing.JTextField();
        btnBrAdd = new javax.swing.JButton();
        btnBrUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBrDelete = new javax.swing.JButton();
        txtBBid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLgOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 750));
        setResizable(false);

        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        btnCView.setText("View All");
        btnCView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCViewActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Name");

        txtCName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCNameKeyPressed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCustomer);

        btnCSearch.setText("Search");
        btnCSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSearchActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Customer Information");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtCName))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCView, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(btnCSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );

        btnCAdd.setText("Add");
        btnCAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAddActionPerformed(evt);
            }
        });

        btnCUpdate.setText("Update");
        btnCUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUpdateActionPerformed(evt);
            }
        });

        btnCDelete.setText("Delete");
        btnCDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDeleteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Name");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Address");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Item");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Branch Id");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });

        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Customer ID");

        txtCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtItem, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txtCustName, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txtBrId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(btnCDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Customer", jPanel2);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        btnCalcSal.setText("Calculate Salary");
        btnCalcSal.setToolTipText("");
        btnCalcSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcSalActionPerformed(evt);
            }
        });

        btnEView.setText("View All");
        btnEView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEViewActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Name");

        txtEName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtENameActionPerformed(evt);
            }
        });
        txtEName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtENameKeyPressed(evt);
            }
        });

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblEmployee);

        btnESearch.setText("Search");
        btnESearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnESearchActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Employee Information");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtEName))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEView, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(btnESearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnESearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnEView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Employee Id");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Name");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("NIC");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Contact");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Base Salary");

        txtEid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEidActionPerformed(evt);
            }
        });

        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });

        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });

        txtEContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEContactActionPerformed(evt);
            }
        });

        btnEAdd.setText("Add");
        btnEAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEAddActionPerformed(evt);
            }
        });

        btnEUpdt.setText("Update");
        btnEUpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEUpdtActionPerformed(evt);
            }
        });

        btnEDelete.setText("Delete");
        btnEDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel23))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEContact)
                                    .addComponent(txtNIC)
                                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEBSal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEUpdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCalcSal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtEContact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEBSal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnEUpdt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnEDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnCalcSal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jTabbedPane4.addTab("Employee", jPanel3);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnVUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVUpdate.setText("Update");
        btnVUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVUpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Vehicle Id");

        txtVIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVInActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Vehicle Type");

        cmbVType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Car", "Van", "Lorry", " " }));
        cmbVType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVTypeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Insuarance No");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Insuarance Expiary Date");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Search By");

        buttonGroup1.add(type);
        type.setText("Type");

        buttonGroup1.add(insNo);
        insNo.setText("Insuarance No");

        txtVehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVehicleKeyPressed(evt);
            }
        });

        btnVSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVSearch.setText("Search");
        btnVSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVSearchActionPerformed(evt);
            }
        });

        btnVAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVAdd.setText("Add");
        btnVAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVAddActionPerformed(evt);
            }
        });

        btnVDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVDelete.setText("Delete");
        btnVDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVDeleteActionPerformed(evt);
            }
        });

        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehicleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVehicle);

        btnVView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVView.setText("View All");
        btnVView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVViewActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Vehicle Details");

        txtVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insNo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(355, 355, 355)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addComponent(btnVView))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbVType, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVid, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtVinExp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtVIn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnVUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnVDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnVAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)))))
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(type)
                            .addComponent(insNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVView, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(txtVid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVType, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(btnVAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVIn, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVinExp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(251, 251, 251))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnVUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnVDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(63, 495, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)))))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Vehicle", jPanel4);

        txtBBrId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Branch Details");

        tblBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBranchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBranch);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Branch Name");

        txtBrName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrNameKeyPressed(evt);
            }
        });

        btnBSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBSearch.setText("Search");
        btnBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSearchActionPerformed(evt);
            }
        });

        btnBView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBView.setText("View All");
        btnBView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(txtBrName, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        bnamebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnamebox.setText("Branch Name");

        baddressbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baddressbox.setText("Branch Address");

        bcontactbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcontactbox.setText("Branch Contact ");

        txtBBrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBBrNameActionPerformed(evt);
            }
        });

        txtBBrAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBBrAddressActionPerformed(evt);
            }
        });

        btnBrAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrAdd.setText("Add New");
        btnBrAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrAddActionPerformed(evt);
            }
        });

        btnBrUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrUpdate.setText("Update ");
        btnBrUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Branch ID");

        btnBrDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrDelete.setText("Delete");
        btnBrDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrDeleteActionPerformed(evt);
            }
        });

        txtBBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBBidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtBBrIdLayout = new javax.swing.GroupLayout(txtBBrId);
        txtBBrId.setLayout(txtBBrIdLayout);
        txtBBrIdLayout.setHorizontalGroup(
            txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtBBrIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txtBBrIdLayout.createSequentialGroup()
                        .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bnamebox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(baddressbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bcontactbox, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtBBrIdLayout.createSequentialGroup()
                                .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBBrAddress)
                                    .addComponent(txtBBrContact)
                                    .addComponent(txtBBrName, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBrDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBrUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBrAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtBBid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        txtBBrIdLayout.setVerticalGroup(
            txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtBBrIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtBBrIdLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBBid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bnamebox)
                            .addComponent(txtBBrName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtBBrIdLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtBBrIdLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(txtBBrIdLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBBrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baddressbox))
                        .addGap(18, 18, 18)
                        .addGroup(txtBBrIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBBrContact, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcontactbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jTabbedPane4.addTab("Branch", txtBBrId);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("DMK Distributors & Transporters");

        btnLgOut.setText("Log out");
        btnLgOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLgOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLgOut)
                .addGap(85, 85, 85))
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnLgOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.getAccessibleContext().setAccessibleName("Branch");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAddActionPerformed
        String cid = txtCid.getText();
        String cn = txtCustName.getText();
        String ca = txtAddress.getText();
        String ci = txtItem.getText();
        String cb = txtBrId.getText();

        Customer c = new Customer(cid, cn, ca, ci, cb);

        if (cid.length() == 0 || cn.length() == 0 || ca.length() == 0 || ci.length() == 0 || cb.length() == 0) {
            c.Validate(cid.length(), cn.length(), ca.length(), ci.length(), cb.length());
        } else {
            c.addc();
            ctableload();
            //13-02-2018
            txtCustName.setText("");
            txtAddress.setText("");
            txtItem.setText("");
            txtBrId.setText("");
        }

    }//GEN-LAST:event_btnCAddActionPerformed

    private void txtBBrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBBrNameActionPerformed
        txtBBrAddress.requestFocusInWindow();
    }//GEN-LAST:event_txtBBrNameActionPerformed

    private void btnBrAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrAddActionPerformed
        String i = txtBBid.getText(); //duplicate entry
        String n = txtBBrName.getText();
        String a = txtBBrAddress.getText();
        String c = txtBBrContact.getText();

        Branch b = new Branch(i, n, a, c);

        if (i.length() == 0 || n.length() == 0 || a.length() == 0 || c.length() == 0) {
            b.Validate(i.length(), n.length(), a.length(), c.length());
        } else {
            b.addb();
            btableload();
            //Setting the fields empty after a sucessfull insersion
            txtBBrName.setText("");
            txtBBrAddress.setText("");
            txtBBrContact.setText("");

        }
    }//GEN-LAST:event_btnBrAddActionPerformed

    private void tblBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBranchMouseClicked
        int row = tblBranch.getSelectedRow();

        String bid = tblBranch.getValueAt(row, 0).toString();
        String bn = tblBranch.getValueAt(row, 1).toString();
        String ba = tblBranch.getValueAt(row, 2).toString();
        String bc = tblBranch.getValueAt(row, 3).toString();

        txtBBid.setText(bid);
        txtBBrName.setText(bn);
        txtBBrAddress.setText(ba);
        txtBBrContact.setText(bc);
    }//GEN-LAST:event_tblBranchMouseClicked

    private void btnBrUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrUpdateActionPerformed
        //check whether the update is wanted
        //instead of add
        int op = JOptionPane.showConfirmDialog(null, "Do you really want to update ");
        if (op == 0) {
            Branch bu = new Branch();

            String bId = txtBBid.getText();
            String n2 = txtBBrName.getText();
            String a2 = txtBBrAddress.getText();
            String c2 = txtBBrContact.getText();

            bu.updateb(n2, a2, c2, bId); //Update method call
            btableload(); //Table loading after updating

        }

    }//GEN-LAST:event_btnBrUpdateActionPerformed

    private void btnBrDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrDeleteActionPerformed
        //checking whether you really want to delete
        //instead of add
        int op_ = JOptionPane.showConfirmDialog(null, "Do you really want to delete");
        if (op_ == 0) {
            Branch bd = new Branch();
            String id = txtBBid.getText();

            bd.deleteb(id);
            btableload();
        }
    }//GEN-LAST:event_btnBrDeleteActionPerformed

    private void btnBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSearchActionPerformed
        Branch bs = new Branch();
        String sch = txtBrName.getText();
        //Search method call and displaying the result in the table
        tblBranch.setModel(DbUtils.resultSetToTableModel(bs.searchb(sch)));

    }//GEN-LAST:event_btnBSearchActionPerformed

    private void txtVInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVInActionPerformed
        txtVinExp.requestFocus();
    }//GEN-LAST:event_txtVInActionPerformed

    private void btnVSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVSearchActionPerformed
        Vehicle v = new Vehicle();
        String sch = txtVehicle.getText();
        if (type.isSelected()) {
            tblVehicle.setModel(DbUtils.resultSetToTableModel(v.searchv(sch)));
        } else {
            tblVehicle.setModel(DbUtils.resultSetToTableModel(v.searchva(sch)));
        }
    }//GEN-LAST:event_btnVSearchActionPerformed

    private void btnVAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVAddActionPerformed
        String vid = txtVid.getText();
        String vtype = cmbVType.getSelectedItem().toString();
        String vInstype = txtVIn.getText();
        String vIExpDate = txtVinExp.getText();
        Vehicle v;
        v = new Vehicle(vid, vtype, vInstype, vIExpDate);

        if (vid.isEmpty() || vtype.isEmpty() == true || vInstype.isEmpty() == true || vIExpDate.isEmpty() == true) {
            v.validate(vid.length(), vtype.length(), vInstype.length(), vIExpDate.length());
        } else {
            v.addv();
            vtableload();
            cmbVType.setSelectedIndex(0);
            txtVIn.setText("");
            txtVinExp.setText("");

        }
    }//GEN-LAST:event_btnVAddActionPerformed

    private void tblVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehicleMouseClicked
        int row_ = tblVehicle.getSelectedRow();

        String vid = tblVehicle.getValueAt(row_, 0).toString();
        String vt_ = tblVehicle.getValueAt(row_, 1).toString();
        String vin_ = tblVehicle.getValueAt(row_, 2).toString();
        String ved_ = tblVehicle.getValueAt(row_, 3).toString();

        txtVid.setText(vid);
        cmbVType.setSelectedItem(vt_);
        txtVIn.setText(vin_);
        txtVinExp.setText(ved_);
    }//GEN-LAST:event_tblVehicleMouseClicked

    private void btnVUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVUpdateActionPerformed
        int op_ = JOptionPane.showConfirmDialog(null, "Do you really want to update ");
        if (op_ == 0) {
            Vehicle vu = new Vehicle();
            String vid2 = txtVid.getText();
            String vt2 = cmbVType.getSelectedItem().toString();
            String vin2 = txtVIn.getText();
            String vied = txtVinExp.getText();

            vu.updatev(vid2, vt2, vin2, vied);
            vtableload();
        }
    }//GEN-LAST:event_btnVUpdateActionPerformed

    private void btnVDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVDeleteActionPerformed
        int Op_ = JOptionPane.showConfirmDialog(null, "Do you really want to delete");
        if (Op_ == 0) {
            Vehicle vd = new Vehicle();
            String id = txtVid.getText();

            vd.deletev(id);
            vtableload();
        }
    }//GEN-LAST:event_btnVDeleteActionPerformed

    private void btnCViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCViewActionPerformed
        ctableload();
    }//GEN-LAST:event_btnCViewActionPerformed

    private void btnCUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUpdateActionPerformed
        int Op_ = JOptionPane.showConfirmDialog(null, "Do you really want to update ");
        if (Op_ == 0) {
            Customer cu = new Customer();

            String cId = txtCid.getText();
            String cN = txtCustName.getText();
            String cA = txtAddress.getText();
            String cI = txtItem.getText();
            String cBid = txtBrId.getText();

            cu.updatec(cId, cN, cA, cI, cBid);
            ctableload();
        }

    }//GEN-LAST:event_btnCUpdateActionPerformed

    private void btnCDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDeleteActionPerformed
        int OP = JOptionPane.showConfirmDialog(null, "Do you really want to delete");
        if (OP == 0) {
            Customer cd = new Customer();
            String CID = txtCid.getText();

            cd.deletec(CID);
            ctableload();
        }
    }//GEN-LAST:event_btnCDeleteActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        int Row_ = tblCustomer.getSelectedRow();

        String cid_ = tblCustomer.getValueAt(Row_, 0).toString();
        String cn__ = tblCustomer.getValueAt(Row_, 1).toString();
        String ca__ = tblCustomer.getValueAt(Row_, 2).toString();
        String ci__ = tblCustomer.getValueAt(Row_, 3).toString();
        String cbi__ = tblCustomer.getValueAt(Row_, 4).toString();

        txtCid.setText(cid_);
        txtCustName.setText(cn__);
        txtAddress.setText(ca__);
        txtItem.setText(ci__);
        txtBrId.setText(cbi__);
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnCSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSearchActionPerformed
        Customer cs = new Customer(); //invalid entry
        String sch = txtCName.getText();

        tblCustomer.setModel(DbUtils.resultSetToTableModel(cs.searchc(sch)));
    }//GEN-LAST:event_btnCSearchActionPerformed

    private void btnBViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBViewActionPerformed
        btableload();
    }//GEN-LAST:event_btnBViewActionPerformed

    private void btnVViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVViewActionPerformed
        vtableload();
    }//GEN-LAST:event_btnVViewActionPerformed

    private void btnCalcSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcSalActionPerformed
        CalcSalary cs = new CalcSalary();
        cs.setVisible(true);
    }//GEN-LAST:event_btnCalcSalActionPerformed

    private void btnLgOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLgOutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLgOutActionPerformed

    private void txtCNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Customer cs = new Customer();
            String sch = txtCName.getText();

            tblCustomer.setModel(DbUtils.resultSetToTableModel(cs.searchc(sch)));
        }
    }//GEN-LAST:event_txtCNameKeyPressed

    private void txtCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidActionPerformed
        txtCustName.requestFocusInWindow();
    }//GEN-LAST:event_txtCidActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        txtAddress.requestFocusInWindow();
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtItem.requestFocusInWindow();
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        txtBrId.requestFocusInWindow();
    }//GEN-LAST:event_txtItemActionPerformed

    private void txtBrNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //invalid entry
            Branch bs = new Branch();
            String sch = txtBrName.getText();
            //Search method call and displaying the result in the table
            tblBranch.setModel(DbUtils.resultSetToTableModel(bs.searchb(sch)));
        }
    }//GEN-LAST:event_txtBrNameKeyPressed

    private void txtBBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBBidActionPerformed
        txtBBrName.requestFocusInWindow();
    }//GEN-LAST:event_txtBBidActionPerformed

    private void txtBBrAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBBrAddressActionPerformed
        txtBBrContact.requestFocusInWindow();
    }//GEN-LAST:event_txtBBrAddressActionPerformed

    private void txtVehicleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Vehicle v = new Vehicle();
            String sch = txtVehicle.getText();
            if (type.isSelected()) {
                tblVehicle.setModel(DbUtils.resultSetToTableModel(v.searchv(sch)));
            } else {
                tblVehicle.setModel(DbUtils.resultSetToTableModel(v.searchva(sch)));
            }
        }
    }//GEN-LAST:event_txtVehicleKeyPressed

    private void txtVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidActionPerformed
        cmbVType.requestFocus();
    }//GEN-LAST:event_txtVidActionPerformed

    private void cmbVTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVTypeActionPerformed
        txtVIn.requestFocus();
    }//GEN-LAST:event_cmbVTypeActionPerformed

    private void btnEViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEViewActionPerformed
        etableload();
    }//GEN-LAST:event_btnEViewActionPerformed

    private void txtENameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtENameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Employee e = new Employee(); //invalid entry
            String sch = txtEName.getText();

            // tblEmployee.setModel(DbUtils.resultSetToTableModel(e.searche(sch)));
        }
    }//GEN-LAST:event_txtENameKeyPressed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        int Row_ = tblEmployee.getSelectedRow();

        String eid_ = tblEmployee.getValueAt(Row_, 0).toString();
        String n__ = tblEmployee.getValueAt(Row_, 1).toString();
        String ic__ = tblEmployee.getValueAt(Row_, 2).toString();
        String cntct__ = tblEmployee.getValueAt(Row_, 3).toString();
        String sal__ = tblEmployee.getValueAt(Row_, 4).toString();

        txtEid.setText(eid_);
        txtEmpName.setText(n__);
        txtNIC.setText(ic__);
        txtEContact.setText(cntct__);
        txtEBSal.setText(sal__);
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void btnESearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnESearchActionPerformed
        Employee e = new Employee(); //invalid entry
        String sch = txtEName.getText();

        tblEmployee.setModel(DbUtils.resultSetToTableModel(e.searchE(sch)));
    }//GEN-LAST:event_btnESearchActionPerformed

    private void txtEidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEidActionPerformed
        txtEmpName.requestFocus();
    }//GEN-LAST:event_txtEidActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        txtNIC.requestFocus();
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        txtEContact.requestFocus();
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtEContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEContactActionPerformed
        txtEBSal.requestFocus();
    }//GEN-LAST:event_txtEContactActionPerformed

    private void btnEAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEAddActionPerformed

        String eId = txtEid.getText();
        String n = txtEmpName.getText();
        String ic = txtNIC.getText();
        String cntct = txtEContact.getText();
        String s = txtEBSal.getText();
        double sal = Double.parseDouble(s);

        Employee e = new Employee(eId, n, ic, cntct, sal);

        if (eId.length() == 0 || n.length() == 0 || ic.length() == 0 || cntct.length() == 0 || s.length() == 0) {
            e.Validate(eId.length(), n.length(), ic.length(), cntct.length(), s.length());
        } else {
            e.addE();
            etableload();
            //13-02-2018
            txtEid.setText("");
            txtEmpName.setText("");
            txtNIC.setText("");
            txtEContact.setText("");
            txtEBSal.setText("");
        }

    }//GEN-LAST:event_btnEAddActionPerformed

    private void btnEUpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEUpdtActionPerformed
        int Op_ = JOptionPane.showConfirmDialog(null, "Do you really want to update ");
        if (Op_ == 0) {
            Employee e = new Employee();
            double sal = 0;

            String eId = txtEid.getText();
            String n = txtEmpName.getText();
            String ic = txtNIC.getText();
            String cntct = txtEContact.getText();
            String s = txtEBSal.getText();
            if (s.isEmpty()) {
                sal = 0;
            } else {
                sal = Double.parseDouble(s);
            }

            e.updateE(eId, n, ic, cntct, sal);
            etableload();
        }
    }//GEN-LAST:event_btnEUpdtActionPerformed

    private void btnEDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDeleteActionPerformed
        int OP = JOptionPane.showConfirmDialog(null, "Do you really want to delete");
        if (OP == 0) {
            Employee e = new Employee();
            String eID = txtEid.getText();

            e.deleteE(eID);
            etableload();
        }
    }//GEN-LAST:event_btnEDeleteActionPerformed

    private void txtENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtENameActionPerformed
        Employee e = new Employee(); //invalid entry
        String sch = txtEName.getText();

        tblEmployee.setModel(DbUtils.resultSetToTableModel(e.searchE(sch)));
    }//GEN-LAST:event_txtENameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baddressbox;
    private javax.swing.JLabel bcontactbox;
    private javax.swing.JLabel bnamebox;
    private javax.swing.JButton btnBSearch;
    private javax.swing.JButton btnBView;
    private javax.swing.JButton btnBrAdd;
    private javax.swing.JButton btnBrDelete;
    private javax.swing.JButton btnBrUpdate;
    private javax.swing.JButton btnCAdd;
    private javax.swing.JButton btnCDelete;
    private javax.swing.JButton btnCSearch;
    private javax.swing.JButton btnCUpdate;
    private javax.swing.JButton btnCView;
    private javax.swing.JButton btnCalcSal;
    private javax.swing.JButton btnEAdd;
    private javax.swing.JButton btnEDelete;
    private javax.swing.JButton btnESearch;
    private javax.swing.JButton btnEUpdt;
    private javax.swing.JButton btnEView;
    private javax.swing.JButton btnLgOut;
    private javax.swing.JButton btnVAdd;
    private javax.swing.JButton btnVDelete;
    private javax.swing.JButton btnVSearch;
    private javax.swing.JButton btnVUpdate;
    private javax.swing.JButton btnVView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbVType;
    private javax.swing.JRadioButton insNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tblBranch;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBBid;
    private javax.swing.JTextField txtBBrAddress;
    private javax.swing.JTextField txtBBrContact;
    private javax.swing.JPanel txtBBrId;
    private javax.swing.JTextField txtBBrName;
    private javax.swing.JTextField txtBrId;
    private javax.swing.JTextField txtBrName;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtEBSal;
    private javax.swing.JTextField txtEContact;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtVIn;
    private javax.swing.JTextField txtVehicle;
    private javax.swing.JTextField txtVid;
    private javax.swing.JTextField txtVinExp;
    private javax.swing.JRadioButton type;
    // End of variables declaration//GEN-END:variables
}
